### ISSUE TITLE
Undefined SC_MAX_MARGIN 

### ISSUE THREAD

**Issue by imakin** [codebrainz/overview-plugin#1]
Hello,, this is a nice plugin. But i was recently trying to compile and it gave me an error about undefined macro SC_MAX_MARGIN in overview/overviewscintilla.c
(pulled this source 14:30 March, 11)
am i missing something? 

```
make[1]: Entering directory '/data/makin/geany_lain/overview-plugin/overview'
  CC       overviewcolor.lo
  CC       overviewplugin.lo
  CC       overviewprefs.lo
  CC       overviewprefspanel.lo
  CC       overviewscintilla.lo
overviewscintilla.c: In function 'overview_scintilla_update_sci':
overviewscintilla.c:926:24: error: 'SC_MAX_MARGIN' undeclared (first use in this function)
   for (gint i = 0; i < SC_MAX_MARGIN; i++)
                        ^
overviewscintilla.c:926:24: note: each undeclared identifier is reported only once for each function it appears in
```

thankyou

**Comment by codebrainz** [comment]
It's this one:
https://github.com/geany/geany/blob/master/scintilla/include/Scintilla.h#L160

It should be available since here:
https://github.com/geany/geany/commit/e88c03d266e1b8d4279a76481d03c54a76fd961d#diff-f6069c87d74c25140a72a5766df10f04R151

Anyway, you can just replace that `SC_MAX_MARGIN` with `4`, I might do same in the code if it's too new of a symbol.

**Comment by codebrainz** [comment]
Thanks for testing/reporting!
