### ISSUE TITLE
Doesn't load in Ubuntu Geany 1.24.1

### ISSUE THREAD

**Issue by amagnolo** [codebrainz/overview-plugin#13]
When I try to load the plugin the log says:
Geany-INFO: Plugin "/usr/lib/x86_64-linux-gnu/geany/overview.so" requires a newer version of Geany (API >= v224)

Geany is version 1.24.1 from the Ubuntu repositories. I even tried to build the latest geany myself but with the same result. My exact ubuntu distribution is Lubuntu 14.10.

**Comment by b4n** [comment]
The plugin depends on the current development version of Geany, not the latest release.

**Comment by amagnolo** [comment]
OK, I look forward to see this very promising plugin in a stable release. Meanwhile I suggest you write the version it depends on in the README.md.
Best regards,
Alessandro Magnolo

**Comment by codebrainz** [comment]
@amagnolo good idea about documenting it. By the way, if you want to use it with 1.24, you can manually undo the change in 8f2e408973cbc6b52212f647f669a9d5a8468e0f. As long as you're on Linux it should work (because of a technicality).

**Comment by codebrainz** [comment]
@b4n, like this work? is it a bad idea for any reason?

``` c
#if GEANY_API_VERSION <= 224
PLUGIN_VERSION_CHECK(211)
#else 
PLUGIN_VERSION_CHECK(224)
#endif
```

**Comment by b4n** [comment]
it sounds silly, checking for something only if you have it…
it's too late now for me to clearly check the implications so whether it would actually make sense or not, but it would probably at least not be worse than `PLUGIN_VERSION_CHECK(211)` alone from a practical POV.  Though you probably meant `<` rather than `<=` in the check.

**Comment by amagnolo** [comment]
I did the version check change and now the plugin works, but whenever I try to open the find dialog the following error occurs:
(geany:31305): Geany-CRITICAL **: document_grab_focus: assertion 'doc != NULL' failed
Then eventually Geany dies with Segmentation fault.

**Comment by codebrainz** [comment]
Did you by any chance put the sidebar on the left side?

**Comment by amagnolo** [comment]
No, I didn't.
Now I have tried it and it says: 
*\* (geany:26860): CRITICAL **: Refusing to swap Overview into left position because your Geany version isn't new enough to support this without crashing hard.

**Comment by codebrainz** [comment]
Ok, that's why I asked, because older Geany version it won't work on the left, but it's supposed to show that message, if it didn't, it would show assertion failures like you had and then crash.

**Comment by codebrainz** [comment]
Best way to troubleshoot would be to unload all plugins, exit Geany, then start Geany, activate the Overview plugin (and optionally restart Geany again), so it's only that plugin and if it still does. If it keeps causing warnings and then crashing, I'd need to be able to somehow reproduce unless you could get a meaningful GDB backtrace (which is unlikely since it sounds like it happens later, probably indirectly by the main loop).

**Comment by amagnolo** [comment]
I tried this: 
- delete ~/.config/geany/ so it will start without plugins and with default settings
- start geany and enable overview plugin
- restart geany: the console shows
  (geany:25294): Geany-CRITICAL **: document_grab_focus: assertion 'doc != NULL' failed
- click menu "Search" "Find...": the console shows
  (geany:25294): Geany-CRITICAL **: search_show_find_dialog: assertion 'doc != NULL' failed
- close geany window: the console shows
  (geany:25294): Geany-CRITICAL **: remove_page: assertion 'doc != NULL' failed
- then geany exits with no crash.

I'm sorry to be unable to provide a more detailed report. Maybe I'll just wait for the next geany version to be released.
